# 订阅cmdSub：服务器发送过来的控制指令，做出相应操作
# 发布dataPush：主动向服务器推送数据消息
# 发布statusPush：主动向服务器推送状态消息

stomp:
  host: 192.168.120.99
  port: 61613
  name: admin
  passwd: sealan
  timeout: 10

topic:
  moduleName: 3DLidar
  cmdSub: /topic/cmd.3DLidar.post
  dataPush: /topic/data.push
  cmdReply: /topic/cmd.reply
  statusPush: /topic/status.push
  diseasePush: /topic/data.disease.pic

hanningRmmsNs:
  tcpIp: 192.168.1.92
  tcpPortRmms: 8000
  tcpPortDaq: 8500
  tcpPortSync: 8300
  tcpPortScanner: 8400
  tcpPortGPS: 8600
